import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsNumber, IsOptional, IsString } from 'class-validator';

export class QrDto {
  @IsString()
  @ApiProperty({ example: 'white', description: 'Choose Category' })
  category: string;

  @IsString()
  @ApiProperty({ example: 'Mai Temple', description: 'Known For' })
  knownFor: string;

  @IsString()
  @ApiProperty({ example: 'Temple', description: 'Name of Qrlekh Info' })
  name: string;

  @IsString()
  @IsOptional()
  @ApiProperty({
    example: 'temple',
    description: 'should be generated by name and can be unique',
  })
  slug: string;

  @IsString()
  @ApiProperty({
    example: 'Temple ',
    description: 'Give the short detail of Temple?',
  })
  desc: string;

  @IsString()
  @ApiProperty({
    example: 'kathamandu',
    description: 'What is the location of Temple?',
  })
  location: string;

  @IsNumber()
  @IsOptional()
  @ApiProperty({ minLength: 1, maxLength: 5, default: 1 })
  rating: number;

  @ApiProperty({ default: false })
  @IsBoolean()
  @IsOptional()
  favourite: boolean;

  @IsOptional()
  @IsBoolean()
  @ApiProperty({ default: false })
  like: boolean;

  @IsOptional()
  @IsBoolean()
  @ApiProperty({ default: false })
  dislike: boolean;

  @IsNumber()
  @IsOptional()
  userId: number;

  @IsNumber()
  tagNameId: number;
}
