import { ApiProperty } from '@nestjs/swagger';
import { IsNumber, IsOptional, IsString } from 'class-validator';

export class QrDto {
  @IsString()
  @ApiProperty({ example: 'Mai Temple', description: 'Known For' })
  knownFor: string;

  @IsString()
  @ApiProperty({ example: 'Temple', description: 'Name of Qrlekh Info' })
  title: string;

  @IsString()
  @IsOptional()
  @ApiProperty({
    example: 'temple',
    description: 'should be generated by name and can be unique',
  })
  slug: string;

  @IsNumber()
  @IsOptional()
  @ApiProperty()
  visitor: number;

  @IsString()
  @ApiProperty({
    example: 'kathamandu',
    description: 'What is the location of Temple?',
  })
  location: string;

  @IsString()
  @ApiProperty({
    example: 'Temple ',
    description: 'Give the short detail of Temple?',
  })
  desc: string;

  @IsOptional()
  @ApiProperty()
  like: number[];

  @IsNumber()
  categoryId: number;
}
